# Form implementation generated from reading ui file 'test.ui'
#
# Created by: PyQt6 UI code generator 6.4.2
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(400, 300)
        self.pyqt6_pushButton = QtWidgets.QPushButton(parent=Form)
        self.pyqt6_pushButton.setGeometry(QtCore.QRect(90, 70, 75, 24))
        self.pyqt6_pushButton.setObjectName("pyqt6_pushButton")

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Form"))
        self.pyqt6_pushButton.setText(_translate("Form", "text_PushButton"))
