# Generated by Django 4.2 on 2024-05-01 20:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userapp', '0003_myuser_birthday'),
    ]

    operations = [
        migrations.AddField(
            model_name='myuser',
            name='oauth_github_id',
            field=models.CharField(max_length=255, null=True, unique=True),
        ),
    ]
