import type { Metadata } from "next";
import "./globals.css";
import ThemeProvider from "@/components/provider/theme-provider";


export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`
          antialiased`}
      >
        <ThemeProvider
          attribute="class"
          defaultTheme="dark"
          enableSystem={true}
          value={{ light: "light", dark: "dark" }}
        >
        
        <main className="h-screen">

          {children}
        </main>
        </ThemeProvider>
      </body>
    </html>
  );
}
