# Generated by Django 4.2 on 2024-03-19 14:02

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="DeptModel",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(max_length=20, unique=True, verbose_name="部门名字"),
                ),
                (
                    "address",
                    models.CharField(
                        blank=True, max_length=100, null=True, verbose_name="部门地址"
                    ),
                ),
                (
                    "parent",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="login.deptmodel",
                    ),
                ),
            ],
            options={
                "verbose_name": "部门表",
                "verbose_name_plural": "部门表",
                "db_table": "t_dept",
                "ordering": ["id"],
            },
        ),
        migrations.CreateModel(
            name="User",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("is_delete", models.BooleanField(default=False)),
                ("username", models.CharField(max_length=16, unique=True)),
                ("password", models.CharField(max_length=40)),
                (
                    "email",
                    models.EmailField(
                        blank=True, max_length=254, null=True, unique=True
                    ),
                ),
                ("create_time", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "verbose_name": "用户",
                "verbose_name_plural": "用户",
            },
        ),
        migrations.CreateModel(
            name="Employee",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(max_length=20, unique=True, verbose_name="员工姓名"),
                ),
                (
                    "job",
                    models.CharField(
                        choices=[("MR", "部门经理"), ("CE", "普通雇员"), ("PR", "总裁级别")],
                        default="CE",
                        max_length=2,
                        verbose_name="员工职位",
                    ),
                ),
                (
                    "entry_date",
                    models.DateField(
                        default=datetime.date(2024, 3, 19), verbose_name="入职日期"
                    ),
                ),
                ("sal", models.IntegerField(verbose_name="级别薪资")),
                ("bonus", models.SmallIntegerField(default=0, verbose_name="津贴")),
                ("is_leave", models.BooleanField(default=False, verbose_name="是否离职")),
                (
                    "dept",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="emps_list",
                        to="login.deptmodel",
                        verbose_name="员工所属的部门",
                    ),
                ),
            ],
            options={
                "verbose_name": "员工表",
                "verbose_name_plural": "员工表",
                "db_table": "t_emp",
                "ordering": ["id"],
            },
        ),
    ]
