# Generated by Django 4.2 on 2024-03-19 14:23

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("login", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="employee",
            name="dept",
        ),
        migrations.DeleteModel(
            name="DeptModel",
        ),
        migrations.DeleteModel(
            name="Employee",
        ),
    ]
