# Generated by Django 4.2 on 2024-03-22 20:15

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("login", "0004_loginuser_myuser_delete_user"),
    ]

    operations = [
        migrations.AddField(
            model_name="myuser",
            name="phone_num",
            field=models.CharField(
                blank=True, max_length=11, null=True, verbose_name="手机号"
            ),
        ),
    ]
