# Generated by Django 4.2 on 2024-03-19 14:02

import ckeditor.fields
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Article",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name_en",
                    models.CharField(
                        blank=True, max_length=100, null=True, verbose_name="英文名"
                    ),
                ),
                ("title", models.CharField(max_length=100, verbose_name="标题")),
                ("content", ckeditor.fields.RichTextField(verbose_name="内容")),
                (
                    "img",
                    models.ImageField(
                        blank=True, null=True, upload_to="", verbose_name="图片"
                    ),
                ),
                (
                    "thumb",
                    models.ImageField(
                        blank=True, null=True, upload_to="thumb/", verbose_name="缩略图"
                    ),
                ),
                (
                    "create_time",
                    models.DateTimeField(auto_now_add=True, verbose_name="创建时间"),
                ),
                (
                    "modify_time",
                    models.DateTimeField(auto_now=True, verbose_name="修改时间"),
                ),
                (
                    "source",
                    models.CharField(
                        blank=True, max_length=100, null=True, verbose_name="来源"
                    ),
                ),
                (
                    "look_num",
                    models.PositiveIntegerField(default=0, verbose_name="阅读量"),
                ),
                ("comment_num", models.IntegerField(default=0, verbose_name="评论量")),
                ("like_num", models.IntegerField(default=0, verbose_name="点赞量")),
                (
                    "advertisement",
                    models.BooleanField(default=False, verbose_name="是否广告"),
                ),
                (
                    "author",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="作者",
                    ),
                ),
            ],
            options={
                "verbose_name": "文章",
                "verbose_name_plural": "文章",
            },
        ),
        migrations.CreateModel(
            name="Category",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                ("name_en", models.CharField(blank=True, max_length=100, null=True)),
            ],
            options={
                "verbose_name": "分类",
                "verbose_name_plural": "分类",
            },
        ),
        migrations.CreateModel(
            name="Sentence",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("content", models.TextField()),
            ],
            options={
                "verbose_name": "每日句子",
                "verbose_name_plural": "每日句子",
            },
        ),
        migrations.CreateModel(
            name="Tag",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
            ],
            options={
                "verbose_name": "标签",
                "verbose_name_plural": "标签",
            },
        ),
        migrations.CreateModel(
            name="Comment",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        blank=True, max_length=50, null=True, verbose_name="名字"
                    ),
                ),
                (
                    "email",
                    models.EmailField(
                        blank=True, max_length=255, null=True, verbose_name="邮箱"
                    ),
                ),
                ("content", models.TextField()),
                (
                    "create_time",
                    models.DateTimeField(auto_now_add=True, verbose_name="创建时间"),
                ),
                (
                    "article",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="my_app.article",
                        verbose_name="文章",
                    ),
                ),
            ],
            options={
                "verbose_name": "评论",
                "verbose_name_plural": "评论",
            },
        ),
        migrations.AddField(
            model_name="article",
            name="category_s",
            field=models.ManyToManyField(
                blank=True, null=True, to="my_app.category", verbose_name="分类"
            ),
        ),
        migrations.AddField(
            model_name="article",
            name="tags",
            field=models.ManyToManyField(
                blank=True, null=True, to="my_app.tag", verbose_name="标签"
            ),
        ),
    ]
