# Generated by Django 4.2 on 2024-03-21 07:53

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("my_app", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="article",
            name="category_s",
            field=models.ManyToManyField(
                blank=True, to="my_app.category", verbose_name="分类"
            ),
        ),
        migrations.AlterField(
            model_name="article",
            name="tags",
            field=models.ManyToManyField(
                blank=True, to="my_app.tag", verbose_name="标签"
            ),
        ),
    ]
